<a href="https://colab.research.google.com/github/ArrozConPollo7/queso/blob/main/le_travail.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio #1 :D 

Interacciòn 1:

In [ ]:
lista=[]
i=1
while i<11:
    lista.append(i)
    i=i+1
print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Interacciòn 2:

In [ ]:
lista=[]
i=2
while i<11:
    lista.append(i)
    i=i+1
    if i>10:
      lista.append(1)
print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]


Interacciòn 3:

In [ ]:
lista=[]
i=3
while i<11:
    lista.append(i)
    i=i+1
    if i>10:
      lista.append(1)
      lista.append(2)
print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2]


Interacciòn 4:

In [ ]:
lista=[]
i=4
while i<11:
    lista.append(i)
    i=i+1
    if i>10:
      lista.append(1)
      lista.append(2)
      lista.append(3)
print(lista)

Interacciòn 5:

In [ ]:
lista=[]
i=5
while i<11:
    lista.append(i)
    i=i+1
    if i>10:
      lista.append(1)
      lista.append(2)
      lista.append(3)
      lista.append(4)
print(lista)

Interacciòn 6:

In [ ]:
lista=[]
i=6
while i<11:
    lista.append(i)
    i=i+1
    if i>10:
      lista.append(1)
      lista.append(2)
      lista.append(3)
      lista.append(4)
      lista.append(5)
print(lista)

Interacciòn 7:

In [ ]:
lista=[]
i=7
while i<11:
    lista.append(i)
    i=i+1
    if i>10:
      lista.append(1)
      lista.append(2)
      lista.append(3)
      lista.append(4)
      lista.append(5)
      lista.append(6)
print(lista)

Interacciòn 8:

In [ ]:
lista=[]
i=8
while i<11:
    lista.append(i)
    i=i+1
    if i>10:
      lista.append(1)
      lista.append(2)
      lista.append(3)
      lista.append(4)
      lista.append(5)
      lista.append(6)
      lista.append(7)
print(lista)

Interacciòn 9:

In [ ]:
lista=[]
i=9
while i<11:
    lista.append(i)
    i=i+1
    if i>10:
      lista.append(1)
      lista.append(2)
      lista.append(3)
      lista.append(4)
      lista.append(5)
      lista.append(6)
      lista.append(7)
      lista.append(8)
print(lista)

[9, 10, 1, 2, 3, 4, 5, 6, 7, 8]


Interacciòn 10:

In [ ]:
lista=[]
i=10
while i<11:
    lista.append(i)
    i=i+1
    if i>10:
      lista.append(1)
      lista.append(2)
      lista.append(3)
      lista.append(4)
      lista.append(5)
      lista.append(6)
      lista.append(7)
      lista.append(8)
      lista.append(9)
print(lista)

# Ejercicio #2 :D

In [ ]:
import random

def listaAleatorios(n):
      lista = [0]  * 20
      for i in range(n):
          lista[i] = random.randint(0, 100)
      return lista
      if i==i:
        i=""
aleatorios=listaAleatorios(n)
print(aleatorios)

[93, 94, 96, 32, 5, 25, 3, 55, 2, 61, 68, 52, 4, 71, 99, 63, 0, 4, 72, 3]


# Ejercicio #3 :D

In [ ]:
import random
import numpy as np 
  
matrice = np.random.randint(1000, size=(10, 10)) 

mayor = matrice[0][0]
menor = matrice[0][0]

for fila in matrice:
    for valor in fila:
        if valor > mayor:
            mayor = valor
        if valor < menor:
            menor = valor

print("De la matrice: ")
print("")
print(matrice)
print("")
print(f"le mineur est: {menor} et le plus ancien est: {mayor}")
print("")
Pmayor = np.where(matrice==mayor)
print(Pmayor)
print("")
Pmenor = np.where(matrice==menor)
print(Pmenor)


De la matrice: 

[[360 285 809 145  27  38 957 723 917 152]
 [327 738 487 891  93 926 107 441 668 274]
 [845 224  17  77 990 886 272  19  25 531]
 [222 190 675 219 974 906 109 452 697 998]
 [322 459 287 673 624 458 152 294 285 570]
 [613 306 533 511 658   7 194 172 571 376]
 [866 202 526 392 442 986 160 734 626 481]
 [186  39 605 846 956 356 585 585 502  40]
 [342 565 947 615 114 644  14 371  38 576]
 [659 559 288 583 714 594  63  20 123 966]]

le mineur est: 7 et le plus ancien est: 998

(array([3]), array([9]))

(array([5]), array([5]))


# Ejercicio #4 :D

In [47]:
import random
import numpy as np 
  
matrice = np.random.randint(1000, size=(10, 10)) 

mayor = matrice[0][0]
menor = matrice[0][0]

for fila in matrice:
    for valor in fila:
        if valor > mayor:
            mayor = valor
        if valor < menor:
            menor = valor

print(matrice)

print("")
suma = np.sum(matrice, axis=0)
print("la suma de cada columna es:")
print(suma)

[[638   6 621 449 338 110 807 774 260 685]
 [167  79 415 947 944 274 456 353 991 458]
 [673 461 692 141 502 748  94 122 241 231]
 [709 540 688 893  36 904 768 231 978 179]
 [102 110 932 540 480 675 387 249 323 914]
 [462 277 427 923  62  86 221 197 305 816]
 [326 238 995 788 706 261 262 155 895 936]
 [172 418 499 924 713 977 447 848 677  27]
 [894 256 289 502 483 573 969 199 342 793]
 [973 371 355 604 711  53 459 741 747 391]]

la suma de cada columna es:
[5116 2756 5913 6711 4975 4661 4870 3869 5759 5430]
